name: Build 21.02 67+o and 67+

on:
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: 0 23 * * *      
env:
  UPLOAD_COWTRANSFER: false
  RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build for ${{ matrix.flippy_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - flippy_name: 67+
            release_name: openwrt_s905d_n1_k5.14-67+.img
          - flippy_name: 67+o
            release_name: openwrt_s905d_n1_k5.4-67+o.img
          - flippy_name: 67+plus
            release_name: openwrt_s905d_n1_k5.15-67+plus.img
    
    env:
      FLIPPY_NAME: ${{ matrix.flippy_name }}   
      RELEASE_NAME: ${{ matrix.release_name }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |     
        version=$(curl -s "https://api.github.com/repos/0118Add/OpenWrt-Arm21.02/releases/latest" | awk -F '"' '/tag_name/{print $4}')
        
        echo "version=$version"  >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")"  >> $GITHUB_ENV
        
        sudo chmod  -R 777 /opt
        cp -r ${FLIPPY_NAME}/opt/* /opt
        cd /opt
        git clone https://github.com/unifreq/openwrt_packit        
        cd -
        cp /opt/whoami /opt/openwrt_packit
    
    - name: Download
      run: |
        cd /opt/openwrt_packit
        
        wget  https://github.com/0118Add/OpenWrt-Arm21.02/releases/download/$version/openwrt-armvirt-64-default-rootfs.tar.gz
                
    - name: Check Files
      run: |
        cd /opt/openwrt_packit
        ls
                
    - name: Install the package
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install xz-utils btrfs-progs gawk zip unzip curl dosfstools  uuid-runtime
        sudo -E apt-get -qq install git  git-core
        sudo -E apt-get -qq install pigz
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    
    - name: build img
      run: |
        sudo chmod  -R 777 /opt
        cd /opt/openwrt_packit
        sudo chmod +x mk_s905d_n1.sh
        sudo ./mk_s905d_n1.sh
        
    - name: copy update files
      run: |
        cd /opt/openwrt_packit
        sudo cp files/openwrt-update-amlogic output/openwrt-update-amlogic
        
    - name: pigz -9
      id: pigz
      run: |
        sudo chmod -R 777 /opt/openwrt_packit/output
        cd /opt/openwrt_packit/output
        sudo pigz -9 -p 2 -k *
        rm -rf openwrt-update-amlogic.gz openwrt_s905d_n1_R21.11.11_k5.14.18-flippy-67+.img openwrt_s905d_n1_R21.11.11_k5.15.2-flippy-67+.img openwrt_s905d_n1_R21.11.11_k5.4.159-flippy-67+o.img
        echo "::set-output name=status::success"
    
    - name: Check Files4
      run: |
        cd /opt/openwrt_packit/output
        ls
    
    - name: 编译后硬盘容量
      if: (!cancelled())
      run: df -hT

    - name: Create release
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} 🚀 N1-Openwrt-img | 打包
        allowUpdates: true
        tag: ${{ env.version }}
        commit: main
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          ## 以下为N1官方master分支最新固件（每日上午7时自动编译打包最新固件）
          默认IP：192.168.1.10 默认密码： password
           
 
        artifacts: "/opt/openwrt_packit/output/*"   

    - name: Upload firmware to WeTransfer
      if: steps.gz.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress /opt/openwrt/tmp/$RELEASE_NAME.gz 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
